package org.foosball
import org.foosball.domain.Player
import org.foosball.domain.Team


global java.util.List teams


rule "Naive pairUp players"
    when
    	p1: Player()
    	p2: Player( name != p1.name, p1.handicap <= handicap)
    then
    	//teams.add( new Team(p1,p2));
    	System.out.println(p1);
    	System.out.println(p2);
    	System.out.println("==============================");
        //retract(p1);
        //retract(p2);
end