package org.foosball
import org.foosball.domain.Player
import org.foosball.domain.Team
import function org.foosball.service.Helper.*

global java.util.List teams


rule "Naive pairUp players"
    when
    	p1: Player()
    	p2: Player( name != p1.name, p1.handicap <= handicap)
    	not( Player( handicap < p1.handicap ) )
    	not(Player( handicap  > p2.handicap ))
    	not( Team( playerA == p1 || playerB == p1 ) from teams )     	
    then
    	teamUp(kcontext,p1,p2);
end